# Generated by Django 4.2 on 2023-04-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.CharField(default='placeholder.png', max_length=50, unique=True),
        ),
    ]
