# Generated by Django 4.2 on 2023-04-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_category'),
    ]

    operations = [
    ]
