# Generated by Django 4.2 on 2023-04-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_product_category_alter_product_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='dairy', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default='Random desc', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod',
            field=models.CharField(default='Random desc', max_length=50),
        ),
    ]
