# Generated by Django 4.2 on 2023-04-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_product_productimage1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productImage1',
        ),
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
